name: pb
on:
  push:
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  tests:
    runs-on: ubuntu-18.04
    name: premium rate
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run scripts
        run: |
          python scripts/premium.py ${{ secrets.PB_TOKEN }}